# Generated by Django 4.1.2 on 2023-04-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_logo',
            field=models.ImageField(null=True, upload_to='media/orgs_logo', verbose_name='Organization Logo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_wagtail_url',
            field=models.URLField(null=True),
        ),
    ]
