# Generated by Django 4.1.2 on 2023-04-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_passwordresettoken'),
        ('org_applications', '0002_organization_organization_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_adviser', to='accounts.teacheruser'),
        ),
    ]
