# Generated by Django 4.1.2 on 2023-05-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_applications', '0003_alter_organization_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationapplication',
            name='application_letter',
            field=models.TextField(help_text='Please provide a brief summary of why you want to join the organization, your goals and missions, and how you would like to contribute.', null=True, verbose_name='Application Letter'),
        ),
        migrations.AlterField(
            model_name='organizationapplication',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org_applications.organization', verbose_name='Choice of Organization'),
        ),
    ]
