# Generated by Django 4.1.2 on 2023-03-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_studentuser_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Irregular_Students.irregularstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
            ],
        ),
        migrations.AddField(
            model_name='irregularstudent',
            name='subjects',
            field=models.ManyToManyField(through='Irregular_Students.SubjectGrade', to='accounts.subject'),
        ),
    ]
