# Generated by Django 4.1.2 on 2023-04-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irregular_Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irregularstudent',
            name='academic_period',
            field=models.CharField(blank=True, choices=[('1Q1S', 'First Quarter, 1st Semester'), ('2Q1S', 'Second Quarter, 1st Semester'), ('3Q2S', 'Third Quarter, 2nd Semester'), ('4Q2S', 'Fourth Quarter, 2nd Semester')], max_length=4, null=True),
        ),
    ]
