# Generated by Django 4.1.2 on 2023-04-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Irregular_Students', '0002_irregularstudent_academic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgrade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Irregular_Students.irregularstudent'),
        ),
    ]
