# Generated by Django 4.1.2 on 2023-04-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades_11', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstsem_1stq_11',
            options={'verbose_name': '1st QUarter Grade', 'verbose_name_plural': '1st Quarter Grades'},
        ),
        migrations.AlterModelOptions(
            name='firstsem_2ndq_11',
            options={'verbose_name': '2nd Quarter Grade', 'verbose_name_plural': '2nd Quarter Grades'},
        ),
        migrations.AlterModelOptions(
            name='secondsem_3rdq_11',
            options={'verbose_name': '3rd Quarter Grade', 'verbose_name_plural': '3rd Quarter Grades'},
        ),
        migrations.AlterModelOptions(
            name='secondsem_4thq_11',
            options={'verbose_name': '4th Quarter Grade', 'verbose_name_plural': '4th Quarter Grades'},
        ),
    ]
