# Generated by Django 4.1.2 on 2023-05-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfeedbackmodel',
            name='feedback_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
