# Generated by Django 4.1.2 on 2023-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentuser_section_alter_studentuser_strand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='room_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
