# Generated by Django 4.1.2 on 2023-03-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentsection_room_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='media/image_id'),
        ),
    ]
