# Generated by Django 4.1.2 on 2023-03-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentuser_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='is_email_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
