# Generated by Django 4.1.2 on 2023-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='data_privacy_agreed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='media/image_id', verbose_name='Proof of Enrollment'),
        ),
    ]
