# Generated by Django 4.1.2 on 2023-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentuser_data_privacy_agreed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='data_privacy_agreed',
            field=models.BooleanField(help_text='I agree to the data privacy policy', null=True),
        ),
    ]
