# Generated by Django 4.1.2 on 2023-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentuser_data_privacy_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='data_privacy_agreed',
            field=models.BooleanField(null=True),
        ),
    ]
