# Generated by Django 4.1.2 on 2023-04-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentuser_data_privacy_agreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentuser',
            name='enrollment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.enrollmentstatus'),
        ),
    ]
