# Generated by Django 4.1.2 on 2023-04-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_enrollmentstatus_studentuser_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='data_privacy_agreed',
            field=models.BooleanField(null=True, verbose_name='I agree to the data privacy policy'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='enrollment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.enrollmentstatus', verbose_name='Enrollment Status'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='grade_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentyear', verbose_name='Grade Year'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='lrn',
            field=models.CharField(max_length=15, verbose_name='LRN'),
        ),
        migrations.AlterField(
            model_name='studentyear',
            name='Grade_Year',
            field=models.CharField(max_length=2),
        ),
    ]
