# Generated by Django 4.1.2 on 2023-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_studentuser_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='grade_year',
            field=models.CharField(blank=True, choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2, null=True, verbose_name='Grade Year'),
        ),
    ]
