# Generated by Django 4.1.2 on 2023-04-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_studentuser_grade_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Parent Email Address'),
        ),
    ]
