# Generated by Django 4.1.2 on 2023-04-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentuser_parent_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_students',
            options={'verbose_name': 'Enrolled Student', 'verbose_name_plural': 'Enrolled Students'},
        ),
        migrations.AlterModelOptions(
            name='enrollmentstatus',
            options={'verbose_name': 'Enrollment Status', 'verbose_name_plural': 'Enrollment Statuses'},
        ),
        migrations.AlterModelOptions(
            name='studentsection',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentyear',
            options={'verbose_name': 'Grade Level'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacheruser',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='trackandstrand',
            options={'verbose_name': 'Tracks and Strands', 'verbose_name_plural': 'Tracks and Strands'},
        ),
    ]
