# Generated by Django 4.1.2 on 2023-04-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_db_students_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(max_length=15, verbose_name='LRN')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('parent_email', models.EmailField(max_length=254, null=True, verbose_name='Parent Email Address')),
                ('birthday', models.DateField()),
                ('enrollment_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enrollment Status')),
                ('grade_year', models.CharField(blank=True, max_length=2, null=True, verbose_name='Grade Year')),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Enrolled Student',
                'verbose_name_plural': 'Enrolled Students',
            },
        ),
        migrations.DeleteModel(
            name='Db_Students',
        ),
    ]
