# Generated by Django 4.1.2 on 2023-04-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_enrolled_students_delete_db_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='contact_num',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='teacher_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
