# Generated by Django 4.1.2 on 2023-04-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_teacheruser_contact_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='subject_handle',
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='raw_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
