# Generated by Django 4.1.2 on 2023-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_teacheruser_subject_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='lrn',
            field=models.CharField(max_length=15, null=True, verbose_name='LRN'),
        ),
    ]
