# Generated by Django 4.1.2 on 2023-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_studentuser_age_alter_studentuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='changed_details',
            field=models.BooleanField(null=True),
        ),
    ]
