# Generated by Django 4.1.2 on 2023-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_teacheruser_changed_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled_students',
            name='lrn',
            field=models.CharField(max_length=25, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='lrn',
            field=models.CharField(max_length=25, null=True, verbose_name='ID Number'),
        ),
    ]
