# Generated by Django 4.1.2 on 2023-04-24 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_enrolled_students_lrn_alter_studentuser_lrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='advisory_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_section', to='accounts.studentsection'),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='user_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacheruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
