# Generated by Django 4.1.2 on 2023-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='enrollment_status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular'), ('Balik-aral', 'Balik-Aral')], max_length=50, null=True, verbose_name='Enrollment Status'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='grade_year',
            field=models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2, null=True, verbose_name='Grade Year'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image_id',
            field=models.ImageField(null=True, upload_to='media/image_id', verbose_name='Proof of Enrollment'),
        ),
    ]
