# Generated by Django 4.1.2 on 2023-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_studentuser_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='terms_agreed',
            field=models.BooleanField(null=True, verbose_name='I agree to the terms and conditions'),
        ),
    ]
