# Generated by Django 4.1.2 on 2023-03-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailApp', '0003_alter_articleindexpagelatestarticles_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpagelatestarticles',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailApp.articlepage'),
        ),
    ]
