# Generated by Django 4.1.2 on 2023-04-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailApp', '0005_careerinformationarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerinformationarticle',
            name='enrollment_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerinformationarticle',
            name='enrollment_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
