# Generated by Django 4.1.2 on 2023-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailApp', '0007_facultystaffpage_staffmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='short_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
