# Generated by Django 4.1.2 on 2023-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailApp', '0008_articlepage_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
