# Generated by Django 4.1.2 on 2023-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailApp', '0009_alter_articlepage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghomepage',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orghomepage',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Post date'),
        ),
    ]
