# Generated by Django 4.1.2 on 2023-04-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_range', models.DurationField()),
                ('event_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_calendar.eventlevel')),
            ],
        ),
    ]
