# Generated by Django 4.1.2 on 2023-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='event_range',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_start_date',
            field=models.DateField(null=True),
        ),
    ]
