# Generated by Django 4.1.2 on 2023-04-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_calendar', '0002_remove_calendarevent_event_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_level',
            field=models.CharField(choices=[('IMPORTANT', 'IMPORTANT'), ('REMINDER', 'REMINDER')], max_length=20, null=True),
        ),
    ]
