# Generated by Django 4.1.2 on 2023-04-18 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentuser_parent_email'),
        ('portal_calendar', '0003_alter_calendarevent_event_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsection'),
        ),
    ]
