# Generated by Django 4.1.2 on 2023-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentuser_parent_email'),
        ('portal_calendar', '0004_calendarevent_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='section',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='section',
            field=models.ManyToManyField(null=True, to='accounts.studentsection'),
        ),
    ]
