# Generated by Django 4.1.2 on 2023-04-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_calendar', '0005_remove_calendarevent_section_calendarevent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
