# Generated by Django 4.1.2 on 2023-04-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_calendar', '0006_calendarevent_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name': 'Calendar Event', 'verbose_name_plural': 'Calendar Events'},
        ),
    ]
