# Generated by Django 4.1.2 on 2023-05-18 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodMoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=2, null=True)),
                ('lrn', models.CharField(max_length=15, null=True)),
                ('residence', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('years_stayed', models.CharField(max_length=20, null=True)),
                ('purpose', models.CharField(choices=[('college', 'College Admissions'), ('scholarship', 'Scholarship Applications'), ('transfer', 'Transferring to Other School')], max_length=20, null=True)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('plans', models.TextField(blank=True, null=True)),
                ('transferring_school', models.CharField(blank=True, max_length=50, null=True)),
                ('transferring_strand', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('full_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Good Moral Request',
                'verbose_name_plural': 'Good Moral Requests',
            },
        ),
    ]
