# Generated by Django 4.1.2 on 2023-04-20 04:54

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Body'),
        ),
    ]
