# Generated by Django 4.1.2 on 2023-04-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
    ]
