"""
Django settings for sjlshs_backend project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from django.conf import settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uzp0h5*%j0f$2tg-tx%%_v&jn_*hg*_qh$@a000!0_fmf*_uey'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'https://f49c-112-198-255-43.ngrok-free.app']

CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:8000/'
]

CSRF_TRUSTED_ORIGINS = ['https://f49c-112-198-255-43.ngrok-free.app']
# Application definition


INTERNAL_IPS = [
    '127.0.0.1',
]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'adminlte3',
    'adminlte3_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'crispy_forms',
    'crispy_bootstrap5',
    'ajax_select',
    'import_export',
    'django_otp',
    'two_factor',
    'debug_toolbar',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.contrib.settings',
    'wagtail',
    'reportlab',
    'django_summernote',
    'captcha',
    'django_celery_beat',
    'dbbackup',

    'modelcluster',
    'taggit',   



    # own
    'std_portal',
    'accounts',
    'Grades_11',
    'Grades_12',
    'Irregular_Students',
    'subjects',
    'wagtailApp',
    'portal_calendar',
    'messaging',
    'feedback',
    'org_applications',
    'page_customization',
    'form_requests',
    'attendance',

]


DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/backup_db/'}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'sjlshs_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates/MFSPS/HTML"), os.path.join(BASE_DIR, "postman/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            
        },
    },
]

WSGI_APPLICATION = 'sjlshs_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'student_portal_re',
        'USER': 'root',
        'PASSWORD': 'magnusholmes',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
    },
    'renditions' : {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [    'accounts.auth_backends.EmailBackend',
                                'two_factor.views.core.LRNAuthenticationBackend',
                                
                                'django.contrib.auth.backends.ModelBackend',
                                
                                
                                
                            ]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, '/static/root/')
STATIC_URL = '/static/root/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/'),]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = 'two_factor:setup'

TWO_FACTOR_LOGIN_REDIRECT_URL = 'login-redirect'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

AUTH_USER_MODEL = 'accounts.StudentUser'

TWO_FACTOR_OTP_GATEWAY = 'django_otp.plugins.otp_email.EmailPlugin'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_HOST_USER = 'magnusholmes1026@gmail.com'
EMAIL_HOST_PASSWORD = 'w1aI20OVpQfHBZcd'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'sjlshs.noreply@gmail.com'

OTP_EMAIL_SUBJECT = 'SJLSHS ACCOUNT OTP'

CAPTCHA_IMAGE_SIZE = (300, 50)
CAPTCHA_FONT_SIZE = 50



# POSTMAN

AJAX_LOOKUP_CHANNELS = {
    'postman_users': dict(model='accounts.StudentUser', search_field='username')
}



IMPORT_EXPORT_USE_TRANSACTIONS = True


WAGTAIL_SITE_NAME = 'SJLSHS EDITORIAL SITE'
WAGTAILADMIN_BASE_URL = 'http://sjlshs-editorial.com'
WAGTAILADMIN_USER_LOGIN_FORM = 'wagtailApp.forms.LRNAuthenticationForm'
WAGTAIL_ADMIN_LOGIN_FORM = 'wagtailApp.forms.LRNAuthenticationForm'
WAGTAIL_FRONTEND_LOGIN_URL = 'two_factor:login'


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_TIMEZONE = 'UTC'