# Generated by Django 4.1.2 on 2023-03-09 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('PR2', models.SmallIntegerField(default=0)),
                ('CPAR', models.SmallIntegerField(default=0)),
                ('PHILOSOPHY', models.SmallIntegerField(default=0)),
                ('UCSP', models.SmallIntegerField(default=0)),
                ('EAPP', models.SmallIntegerField(default=0)),
                ('SPECC', models.SmallIntegerField(default=0)),
                ('SPECC2', models.SmallIntegerField(default=0)),
                ('PE', models.SmallIntegerField(default=0)),
                ('lrn', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GradePost4th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2_4th', models.SmallIntegerField(default=0)),
                ('cpar_4th', models.SmallIntegerField(default=0)),
                ('pe_4th', models.SmallIntegerField(default=0)),
                ('spec_4th', models.SmallIntegerField(default=0)),
                ('ucsp_4th', models.SmallIntegerField(default=0)),
                ('philo_4th', models.SmallIntegerField(default=0)),
                ('eapp_4th', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost4th', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradePost3rd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2_3rd', models.SmallIntegerField(default=0)),
                ('cpar_3rd', models.SmallIntegerField(default=0)),
                ('pe_3rd', models.SmallIntegerField(default=0)),
                ('spec_3rd', models.SmallIntegerField(default=0)),
                ('ucsp_3rd', models.SmallIntegerField(default=0)),
                ('philo_3rd', models.SmallIntegerField(default=0)),
                ('eapp_3rd', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost3rd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradePost2nd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2_2nd', models.SmallIntegerField(default=0)),
                ('cpar_2nd', models.SmallIntegerField(default=0)),
                ('pe_2nd', models.SmallIntegerField(default=0)),
                ('spec_2nd', models.SmallIntegerField(default=0)),
                ('ucsp_2nd', models.SmallIntegerField(default=0)),
                ('philo_2nd', models.SmallIntegerField(default=0)),
                ('eapp_2nd', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost2nd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_sub1', models.SmallIntegerField(default=0)),
                ('grade_sub2', models.SmallIntegerField(default=0)),
                ('grade_sub3', models.SmallIntegerField(default=0)),
                ('grade_sub4', models.SmallIntegerField(default=0)),
                ('grade_sub5', models.SmallIntegerField(default=0)),
                ('grade_sub6', models.SmallIntegerField(default=0)),
                ('grade_sub7', models.SmallIntegerField(default=0)),
                ('grade_sub8', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost', to=settings.AUTH_USER_MODEL)),
                ('sub1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub1', to='subjects.coresubjects')),
                ('sub2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub2', to='subjects.coresubjects')),
                ('sub3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub3', to='subjects.coresubjects')),
                ('sub4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub4', to='subjects.coresubjects')),
                ('sub5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub5', to='subjects.coresubjects')),
                ('sub6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub6', to='subjects.coresubjects')),
                ('sub7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub7', to='subjects.specializedsubjects')),
                ('sub8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub8', to='subjects.specializedsubjects')),
            ],
        ),
    ]
