# Generated by Django 4.1.2 on 2023-03-20 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grades_12', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSem_1stQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('PR2', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('CPAR', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('PHILOSOPHY', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('UCSP', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('EAPP', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED_2', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('PE', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('Average', models.IntegerField(blank=True, default=0, null=True)),
                ('lrn', models.CharField(max_length=15)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstsem1stq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirstSem_2ndQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('PR2', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('CPAR', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('PHILOSOPHY', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('UCSP', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('EAPP', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED_2', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('PE', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('Average', models.IntegerField(blank=True, default=0, null=True)),
                ('lrn', models.CharField(max_length=15)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstsem2ndq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSem_3rdQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('III', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('MIL', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('PE4', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('IMMERSION', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED_2', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('Average', models.IntegerField(blank=True, default=0, null=True)),
                ('lrn', models.CharField(max_length=15)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondsem3rdq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSem_4thQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('III', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('MIL', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('PE4', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('IMMERSION', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('SPECIALIZED_2', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('Average', models.IntegerField(blank=True, default=0, null=True)),
                ('lrn', models.CharField(max_length=15)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondsem4thq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='lrn',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub4',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub5',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub6',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub7',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='sub8',
        ),
        migrations.RemoveField(
            model_name='gradepost2nd',
            name='lrn',
        ),
        migrations.RemoveField(
            model_name='gradepost3rd',
            name='lrn',
        ),
        migrations.RemoveField(
            model_name='gradepost4th',
            name='lrn',
        ),
        migrations.DeleteModel(
            name='GradeTest',
        ),
        migrations.DeleteModel(
            name='GradePost',
        ),
        migrations.DeleteModel(
            name='GradePost2nd',
        ),
        migrations.DeleteModel(
            name='GradePost3rd',
        ),
        migrations.DeleteModel(
            name='GradePost4th',
        ),
    ]
