# Generated by Django 4.1.2 on 2023-04-01 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grades_12', '0002_firstsem_1stq_firstsem_2ndq_secondsem_3rdq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsem_1stq',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstsem1stq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firstsem_2ndq',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstsem2ndq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secondsem_3rdq',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondsem3rdq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secondsem_4thq',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondsem4thq', to=settings.AUTH_USER_MODEL),
        ),
    ]
