# Generated by Django 4.1.2 on 2023-04-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades_12', '0003_alter_firstsem_1stq_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstsem_1stq',
            options={'verbose_name': '1st Quarter Grade', 'verbose_name_plural': '1st Quarter Grades'},
        ),
        migrations.AlterModelOptions(
            name='firstsem_2ndq',
            options={'verbose_name': '2nd Quarter Grade', 'verbose_name_plural': '2nd Quarter Grades'},
        ),
        migrations.AlterModelOptions(
            name='secondsem_3rdq',
            options={'verbose_name': '3rd Quarter Grade', 'verbose_name_plural': '3rd Quarter Grades'},
        ),
        migrations.AlterModelOptions(
            name='secondsem_4thq',
            options={'verbose_name': '4th Quarter Grade', 'verbose_name_plural': '4th Quarter Grades'},
        ),
    ]
