# Generated by Django 4.1.2 on 2023-03-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
