# Generated by Django 4.1.2 on 2023-03-25 07:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
