# Generated by Django 4.1.2 on 2023-03-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=models.TextField(null=True),
        ),
    ]
