# Generated by Django 4.1.2 on 2023-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentuser_data_privacy_agreed'),
        ('std_portal', '0004_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Section',
        ),
        migrations.AddField(
            model_name='post',
            name='Section',
            field=models.ManyToManyField(to='accounts.studentsection'),
        ),
    ]
