# Generated by Django 4.1.2 on 2023-04-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0005_remove_post_section_post_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
