# Generated by Django 4.1.2 on 2023-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0006_alter_modules_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='media/modules/additional_resources/thumbnails')),
            ],
        ),
    ]
