# Generated by Django 4.1.2 on 2023-04-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0007_additionalresources'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalresources',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionalresources',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='additionalresources',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/modules/additional_resources/thumbnails'),
        ),
        migrations.AlterField(
            model_name='additionalresources',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
